### ISSUE TITLE
starting server causing error in postgres

### ISSUE THREAD

**Issue by awsmsrc** [stripe-ruby-mock/stripe-ruby-mock#33]
Ive narrowed this behaviour down to when the server is started. It does not happen otherwise. I dont really know what other information i can provide to help but ill happily provide nay other information that i can.

```
/Users/luke/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/blankslate-3.1.2/lib/blankslate.rb:51: warning: undefining `object_id' may cause serious problems
You are using WebMock 1.14.0. VCR is known to work with WebMock >= 1.8.0, < 1.14. It may not work with this version.
/Users/luke/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/activerecord-3.2.13/lib/active_record/connection_adapters/postgresql_adapter.rb:1147:in `translate_exception': undefined method `error_field' for nil:NilClass (NoMethodError)
    from /Users/luke/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract_adapter.rb:284:in `rescue in log'
    from /Users/luke/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/activerecord-3.2.13/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `log'
    from /Users/luke/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/activerecord-3.2.13/lib/active_record/connection_adapters/postgresql_adapter.rb:641:in `query'
    from /Users/luke/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/activerecord-3.2.13/lib/active_record/connection_adapters/postgresql_adapter.rb:777:in `tables'
    from /Users/luke/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/activerecord-3.2.13/lib/active_record/connection_adapters/postgresql_adapter.rb:526:in `ensure in disable_referential_integrity'
    from /Users/luke/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/activerecord-3.2.13/lib/active_record/connection_adapters/postgresql_adapter.rb:526:in `disable_referential_integrity'
    from /Users/luke/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/database_cleaner-1.1.1/lib/database_cleaner/active_record/deletion.rb:57:in `clean'
    from /Users/luke/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/database_cleaner-1.1.1/lib/database_cleaner/base.rb:40:in `clean_with'
    from /Users/luke/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/database_cleaner-1.1.1/lib/database_cleaner/configuration.rb:85:in `block in clean_with'
    from /Users/luke/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/database_cleaner-1.1.1/lib/database_cleaner/configuration.rb:85:in `each'
    from /Users/luke/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/database_cleaner-1.1.1/lib/database_cleaner/configuration.rb:85:in `clean_with'
    from /Users/luke/code/sqwiggle/sqwiggle-web/spec/spec_helper.rb:59:in `block (2 levels) in <top (required)>'
    from /Users/luke/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.5/lib/rspec/core/hooks.rb:21:in `instance_eval'
    from /Users/luke/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.5/lib/rspec/core/hooks.rb:21:in `run'
    from /Users/luke/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.5/lib/rspec/core/hooks.rb:85:in `block in run'
    from /Users/luke/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.5/lib/rspec/core/hooks.rb:85:in `each'
    from /Users/luke/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.5/lib/rspec/core/hooks.rb:85:in `run'
    from /Users/luke/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.5/lib/rspec/core/hooks.rb:446:in `run_hook'
    from /Users/luke/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.5/lib/rspec/core/command_line.rb:27:in `block in run'
    from /Users/luke/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.5/lib/rspec/core/reporter.rb:58:in `report'
    from /Users/luke/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.5/lib/rspec/core/command_line.rb:25:in `run'
    from /Users/luke/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.5/lib/rspec/core/runner.rb:80:in `run'
    from /Users/luke/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.5/lib/rspec/core/runner.rb:17:in `block in autorun'
```

**Comment by MikeRogers0** [comment]
I had this issue and solved it by moving where I was calling `StripeMock.spawn_server` to the top of my `rails_helper.rb`. It now looks like:
````ruby
require 'stripe_mock'
require 'thin'
StripeMock.spawn_server(
  :pid_path => StripeMock.default_server_pid_path,
  :host => '127.0.0.1',
  :port => 4999,
  :server => :thin
)

require 'spec_helper'
require File.expand_path("../../config/environment", __FILE__)
require 'rspec/rails'
````

**Comment by sergey-koba-mobidev** [comment]
I had exactly the same issue and @MikeRogers0  answer solved it
